### ISSUE TITLE
탐색 기능 명세

### ISSUE THREAD

**Issue by QuaRang1225** [imad-project/imad-server#167]
## 탐색 기능 명세 내용

```
다음 내용은 지극히 개인적인  iOS 개발자 입장의 입장이며, 서버 개발자의 상황과 입장에 따라 언제든지 회의하여 수정가능함을 알림.
필요하다면 아이매드 서비스의 모든 분야의 개발자들과 회의 가능
```

### 탐색화면

<img width="300" src="https://github.com/imad-project/imad-server/assets/31721255/94bad579-ee2d-411e-aff2-105a7cf34609"> 

- 해당 기능은 특정 필터와 정렬을 기준으로  작품을 탐색하는 기능
- 탐색화면은 메인화면을 포함한 기본 회면 탭바에 포함 되어있음
### 필터화면
<img width="300" src="https://github.com/imad-project/imad-server/assets/31721255/8a90f9b8-97e2-4ddb-9ea9-fd4349bcd8e8">

- 필터 버튼을 터치 하면 나오는 full bottom sheet
- 필터의 종류는 다음과 같음
    - 평점 범위(사진과 같음)
    - 장르(장르 코드 사용)
    - 개봉연도
    - 국가(국가 코드 사용)
- 확인 버튼을 누를 시 위에서 설정한 필터를 토대로 탐색 요청을 걸도록 설계 요망

### 정렬 화면
<img width="300" src="https://github.com/imad-project/imad-server/assets/31721255/8d1a8cda-17b6-40ef-af08-675af89119ef">

- 정렬 버튼을 터치하면 나오는 bottom sheet
- 정렬 기준은 다음과 같음
     - 인기순(인기 기준 랭킹 산출은 메인화면의 랭킹산출과 동일한 기법으로 선정)
     - 평가순(순수 평점과 리뷰의 갯수로 선정)
     - 평점순
     - 리뷰순
     - 최신순(개봉 혹은 연재 순)
     - 가나다순(혹은 영어 알파벳 순)

**Comment by NCookies** [comment]
해당 기능의 구현은 무기한 보류되었음. #173 참고
