### ISSUE TITLE
Oauth 2.0 소셜 로그인 웹 버전 데이터 못 받음

### ISSUE THREAD

**Issue by NCookies** [imad-project/imad-server#170]
앱에서는 oauth2/authorization/google 링크로 접속 시 응답 데이터의 회원 정보를 받는데 문제 없었지만, 웹에서는 현재로서 방법이 없다. 때문에 이를 해결할 방법을 찾아야 한다.

**Comment by NCookies** [comment]
서버 측에서 소셜 로그인 성공 시 onAuthenticationSuccess() 메소드에서 브라우저에게 토큰 정보를 담은 상태로 redirection 해주면, 리액트에서 해당 데이터를 받아올 수 있다.

![Image](https://github.com/imad-project/imad-server/assets/16646208/e957bb3c-c67a-47af-8702-29e533f3ea81)

- [스프링부트x리액트 '카카오 로그인 하기' (JWT+OAuth2) [2]](https://sudo-minz.tistory.com/78) 참고

**Comment by NCookies** [comment]
해당 내용에 대해 정리한 포스팅 참고

[[IMAD] OAuth2 소셜 로그인 (구글, 네이버, 카카오, 애플)](https://velog.io/@ncookie/IMAD-OAuth2-%EC%86%8C%EC%85%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B5%AC%ED%98%84) 참고

**Comment by Dev-KUN-F** [comment]
의문 종결 Q.E.D

2024년 3월 14일 (목) 오전 12:14, SeungWoo Ryu ***@***.***>님이 작성:
